# Generated by Django 3.1.2 on 2020-10-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='uploads/constructors')),
                ('founded', models.DateField()),
                ('current', models.BooleanField()),
                ('season_points', models.IntegerField(blank=True)),
                ('total_points', models.IntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
                ('total_titles', models.PositiveIntegerField(default=0)),
                ('base', models.CharField(max_length=300)),
                ('races_entered', models.IntegerField(default=0)),
                ('season_driver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_driver', to='drivers.driver')),
                ('season_driver2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_driver', to='drivers.driver')),
            ],
        ),
    ]
