# Generated by Django 3.1.2 on 2020-10-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=200)),
                ('championships', models.PositiveSmallIntegerField()),
                ('total_wins', models.PositiveIntegerField(default=0)),
                ('podiums', models.PositiveIntegerField(default=0)),
                ('current_driver', models.BooleanField()),
                ('career_points', models.IntegerField(default=0)),
                ('season_points', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='uploads/drivers')),
                ('description', models.TextField(blank=True, null=True)),
                ('car_number', models.IntegerField(default=0)),
                ('entries', models.IntegerField(default=0)),
                ('pole_positions', models.IntegerField(default=0)),
                ('fastest_laps', models.IntegerField(default=0)),
            ],
        ),
    ]
