# Generated by Django 3.1.2 on 2020-10-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('circuits', '0001_initial'),
        ('drivers', '0002_driver_season_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='GP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('laps', models.IntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits.circuit')),
                ('second_place_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_place_driver', to='drivers.driver')),
                ('third_place_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_place_driver', to='drivers.driver')),
                ('winning_constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winnging_constructor', to='teams.team')),
                ('winning_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winning_driver', to='drivers.driver')),
            ],
        ),
    ]
